ffi2:
  - accident3
  - alphabet3
  - angel
  - angry
  - angry2
  - angry23
  - angry40
  - angry41
  - animal203
  - annulled3
  - bandaid
  - battery88
  - book97
  - boy11
  - boy12
  - business57
  - camouflage
  - car65
  - certificate7
  - checklist4
  - circuit4
  - confused4
  - cpu
  - cpu1
  - cry1
  - cry2
  - crying7
  - customerservice10
  - doubt3
  - doubts1
  - drinks48
  - education6
  - election3
  - electronic51
  - emoticon101
  - emoticon82
  - emoticon83
  - emoticon98
  - emoticons11
  - family4
  - fear3
  - first21
  - fright
  - furious3
  - graduate2
  - group58
  - handshake3
  - hatchback
  - help9
  - house77
  - illness1
  - inadequacy
  - incompetence
  - indifferent
  - kiss3
  - laughing7
  - laughing8
  - lifesaver28
  - lively
  - love2
  - mad1
  - man282
  - manager3
  - medical43
  - mobile26
  - moustaches1
  - mute24
  - mute3
  - navigation28
  - nerd6
  - nervous
  - owl9
  - palmtrees1
  - panic1
  - pencil32
  - pirate5
  - plus13
  - protection24
  - robot30
  - robotic2
  - rough
  - sad34
  - sad35
  - sad37
  - sad38
  - sad39
  - sad74
  - sad75
  - sad77
  - scary
  - serious3
  - severe
  - silhouette121
  - singing4
  - sleep1
  - sleepness
  - sleepy6
  - smile31
  - smile32
  - smile33
  - smiley41
  - smiley42
  - smiling35
  - smiling36
  - solar12
  - spring13
  - square103
  - stars53
  - student12
  - study7
  - stupor
  - surprise5
  - surprised
  - surprised19
  - surprised21
  - surveillance1
  - suspicions
  - sweat1
  - sweating3
  - tears
  - telephone45
  - think7
  - timidity
  - tongue1
  - tongue2
  - two128
  - two210
  - users53
  - very7
  - wink
  - wink9
  - winking9
  - winners1